Update patch set 2
Patch Set 2:

> Patch Set 2: Verified-1
> 
> Doesn't build:
> ERROR: /Users/lucamilanesio/gerrithub/gerrit/plugins/zookeeper/BUILD:9:1: in deps attribute of java_library rule //plugins/zookeeper:zookeeper__plugin: deps not allowed without srcs; move to runtime_deps?. Since this rule was created by the macro 'gerrit_plugin', the error might have been caused by the macro implementation in /Users/lucamilanesio/gerrithub/gerrit/plugins/zookeeper/BUILD:9:1
> ERROR: Analysis of target '//plugins/zookeeper:zookeeper' failed; build aborted: Analysis of target '//plugins/zookeeper:zookeeper__plugin' failed; build aborted

It's because there must be at leas one *.java file in the src/main/java I don't know if it is possible to create empty project with "gerrit_plugin"

Patch-set: 2
Reviewer: Gerrit User 1005270 <1005270@d5d70762-12d0-45a1-890d-524b12d3f735>